// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOVzyJS-_38UujX7obMT1PrAve1XdR3vc',
    appId: '1:338161220415:web:c1236fbeede644e65f318a',
    messagingSenderId: '338161220415',
    projectId: 'noteappfirebase-6dcf5',
    authDomain: 'noteappfirebase-6dcf5.firebaseapp.com',
    storageBucket: 'noteappfirebase-6dcf5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5MN4KGrxRCRwQp2bN9LAZcrpTRqQCfxQ',
    appId: '1:338161220415:android:4112dc9bb43c521f5f318a',
    messagingSenderId: '338161220415',
    projectId: 'noteappfirebase-6dcf5',
    storageBucket: 'noteappfirebase-6dcf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5_hpxIQI-a6-nRVD1V_CC2Rdo2mLWq7g',
    appId: '1:338161220415:ios:09bd8fc0582a8baf5f318a',
    messagingSenderId: '338161220415',
    projectId: 'noteappfirebase-6dcf5',
    storageBucket: 'noteappfirebase-6dcf5.firebasestorage.app',
    iosBundleId: 'com.example.noteappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5_hpxIQI-a6-nRVD1V_CC2Rdo2mLWq7g',
    appId: '1:338161220415:ios:09bd8fc0582a8baf5f318a',
    messagingSenderId: '338161220415',
    projectId: 'noteappfirebase-6dcf5',
    storageBucket: 'noteappfirebase-6dcf5.firebasestorage.app',
    iosBundleId: 'com.example.noteappFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOVzyJS-_38UujX7obMT1PrAve1XdR3vc',
    appId: '1:338161220415:web:1bc0c2866ad12b015f318a',
    messagingSenderId: '338161220415',
    projectId: 'noteappfirebase-6dcf5',
    authDomain: 'noteappfirebase-6dcf5.firebaseapp.com',
    storageBucket: 'noteappfirebase-6dcf5.firebasestorage.app',
  );
}
